# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-gcp-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-gcp-kubectl
  template:
    metadata:
      labels:
        app: demo-gcp-kubectl
    spec:
      containers:
      - name: demo-gcp-kubectl-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/harrylab-28/demo-gcp-kubectl:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"